Rosalind
mito-practice/GO pull request #1
Opened 2022-06-16 18:15 UTC by blackturtle71

here it coooomes

2022-06-17 10:52 UTC, kpotoh requested changes
Один файл переименуй и апрувну

2022-06-17 10:52 UTC, kpotoh commented on rosalind/0README.md
> +# Rosalind things
Обзови файл, удали ноль. Гитхаб парсит только readme.md & readme.txt и отображает их как превью к директории/репе

2022-06-17 10:52 UTC, kpotoh commented on rosalind/DNAcounting.py
> +GC = ((G + C)/(A + C + G + T)) * 100
Зацени [counter](https://docs.python.org/3/library/collections.html#collections.Counter). С ним проще писать

2022-06-17 10:52 UTC, kpotoh commented on rosalind/GC_content.py
> +    id = dna_seq.id
id в питоне это функция из коробки, посмотри, что она делает. И фактически ты ее перезаписал, это нехорошо. Когда хочешь обозвать переменую индексом, пиши либо индекс чего (seq_id), либо иначе (idx, index)

2022-06-17 10:52 UTC, kpotoh commented on rosalind/GC_content.py
> +    GC_content = ((G + C) / (A + C + G + T)) * 100
GC_content это не snake_case, так что возникает ощущение, что это какой-то класс. Лучше просто в строчных буквах

2022-06-17 10:52 UTC, kpotoh commented on rosalind/HammingDistance.py
> +        if seq1[i] != seq2[i]:
Есть функция zip, посмотри, что она делает, просто для развития

2022-06-17 10:52 UTC, kpotoh commented on rosalind/recurring_rabbits.py
> +    second_gen = rabbit(num_months-2, num_offspring)
посмотри, что такое PEP8 и установи либу/расширегие в пайчарм, которая автоматически его делает

2022-06-17 10:52 UTC, kpotoh commented on rosalind/reverse_complement.py
> +print(dna.reverse_complement())
читер. 
В питоне у строк есть метод translate. Посмотри, как он работает, полезная штука

2022-06-17 11:02 UTC, blackturtle71 commented on rosalind/0README.md
> +# Rosalind things
Готово

2022-06-20 09:57 UTC, kpotoh approved these changes

2022-06-20 09:58 UTC, kpotoh commented
Вливай

2022-06-20 10:52 UTC, merged