HW1
mito-practice/GO pull request #3
Opened 2022-06-20 15:53 UTC by blackturtle71

Очень классное задание. Спасибо. Уверен, что не всё сделал правильно, но хотя бы было интересно

2022-06-20 15:54 UTC, blackturtle71 commented
Да ёпт, почему-то конфликт опять появился. Не умею я гитом пользоваться так, что б ничего не сломать

2022-06-20 15:56 UTC, blackturtle71 commented
А, там часть работы "сделала" Настя. Это на самом деле был я за её ноутом, у меня вчера комп не работал :(

2022-06-21 16:40 UTC, kpotoh requested changes
Все здорово, но. Надо доделать питоновские скрипты из 2 задания. 
- Гэпы собирай более оптивально без накопления лишних данных. Зачем? Потому что иногда у тебя будут попадаться задачи с гигабайтами геномов и простая задача будет считаться десятки минут или даже часы, а это непростительно
- поиск консервативных сайтов тоже поправь. Упрости вычисление и объедини скрипты, подзадача все же одна

2022-06-25 13:25 UTC, blackturtle71 commented on homework/hw1/2/conservative_aa.py
> +                conservative_aa.append(seq[AA])
Сделал всё как ты показывал, классный алгоритм. Всё ещё не сделал порог в 90%, но раз уж сегодня due date, то пока так закоммитил. Если/когда разберусь с порогом, закину при следующем pull-request

2022-06-28 19:09 UTC, kpotoh reviewed
график AA conservativeness.PDF мемный

Отл.
Сливай!

2022-06-28 19:09 UTC, kpotoh commented on homework/hw1/2/conservative_aa.py
> +seq_len = 2368  # len of one seq, obtained manually
Лучше так не делать во избежание снижения универсальности скрипта. Можно же легко получить прочтением первой записи

2022-06-28 19:09 UTC, kpotoh commented on homework/hw1/2/conservative_aa.py
> +    for position, aa in enumerate(prot_seq):
prot_seq это биопитоновский сек. Эмпирическим путем проверял, что если сначала перевести в строчку, а потом итерироваться, будет быстрее работать. Можешь как-нить проверить

2022-06-28 19:09 UTC, kpotoh commented on homework/hw1/2/conservative_aa.py
> +    occurrence.append(v)
можно просто:
aa_name = list(counted_aa.keys())
occurrence = list(counted_aa.values())
хотя у тебя должно работать чуть быстрее на жирных словарях

2022-06-29 08:59 UTC, merged