Hw2
mito-practice/GO pull request #5
Opened 2022-07-06 15:45 UTC by blackturtle71

Вот такой вот код, похоже, что в 2 при нарезке на к-меры есть косяк, так как пентануклеотидов аж ~13000, может что-то проглядел. Про 3 в readme написано вроде всё, что нужно, если что спросишь

2022-07-06 19:52 UTC, kpotoh commented
Есть или нет косяка легко проверить: посмотри на те кмеры, которые ты смог найти. Только ли нуклеотиды в них? Почему часть нуклеотидов ловеркейсом?

2022-07-06 19:57 UTC, blackturtle71 commented
> Есть или нет косяка легко проверить: посмотри на те кмеры, которые ты смог найти. Только ли нуклеотиды в них? Почему часть нуклеотидов ловеркейсом?
Так ты же говорил, что lowercase важен, это какое-то мягкое маскирование, хотя и не понял что именно это значить

2022-07-06 20:11 UTC, blackturtle71 commented
Так, в README забыл указать, что в таблицах с к-мерами есть колонки без хедеров. Это колонки с ди- и мономерами

2022-07-07 11:16 UTC, kpotoh requested changes
Надо доделать. В 1 скрипте ты пытаешься сделать без запихивания все в память, но получается в итоге неправильное решение. Не всегда нужно гнаться за оптимизацией. Я из-за деформации сразу стараюсь думать, как бы сделать проще и быстрее, но у тебя пока не получается, поэтому давай будем больше думать про правильное решение, чем про оптимальное. Во 2 скрипте начало положено правильное, осталось доделать

2022-08-25 12:56 UTC, closed without merging